# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5f8a46677db501ce67e6ea136aed0a313c8ae94383a8404b180112e4d489ef061363d081896eb3e42a0e6d2c41d5782aff9345cca91a7f2f605fedd66237cd

test:
  secret_key_base: 0f1527d2381ec7c1ad9162cc3dbddc102e48ec332348cfc624bf7e225bd673afec0e785eaa1935f4c358ff3a03f38fda11eb358de8db8b1310cb64299fa8ad47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
